### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by pdimitron** [BodenmillerGroup/napari-imc#26]
Hello,

New to using python/anaconda, I installed anaconda on one computer, created a new environment and used pip to install napari-imc. I did the same thing on a different computer and ran into the following error.

`(napari-imc) C:\Users\pdimi>napari
Traceback (most recent call last):
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\Scripts\napari.exe\__main__.py", line 4, in <module>
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\site-packages\napari\__main__.py", line 15, in <module>
    import napari.plugins._npe2 as _npe2
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\site-packages\napari\plugins\__init__.py", line 3, in <module>
    from npe2 import PluginManager as _PluginManager
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\site-packages\npe2\__init__.py", line 8, in <module>
    from ._dynamic_plugin import DynamicPlugin
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\site-packages\npe2\_dynamic_plugin.py", line 19, in <module>
    from ._plugin_manager import PluginManager
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\site-packages\npe2\_plugin_manager.py", line 29, in <module>
    from .manifest._npe1_adapter import NPE1Adapter
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\site-packages\npe2\manifest\_npe1_adapter.py", line 17, in <module>
    ADAPTER_CACHE = Path(user_cache_dir("napari", "napari")) / "npe2" / "adapter_manifests"
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\site-packages\appdirs.py", line 293, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "C:\Users\pdimi\anaconda3\envs\napari-imc\lib\site-packages\appdirs.py", line 480, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: The specified procedure could not be found.`

Does anyone have an idea of where to start to fix this issue?

**Comment by jwindhager** [comment]
Hi @pdimitron, thanks for reaching out!

Huh, unfortunately, I have never seen this issue before. I personally don't work on Windows, so I don't really know where to start. However, I suspect that this is not a problem specifically with napari-imc, but with your system/conda/napari install.

Could you try to create a new environment, in which you only install `napari[all]`? If napari still fails to launch in this case, please reach out to the napari devs - they are very responsive and helpful!

Otherwise, you could try to use conda instead:

    conda install napari napari-imc

Please let me know how this goes!

**Comment by pdimitron** [comment]
Hey @jwindhager,

So I tried to do that, which I believe was essentially what I was running before, but just making the new env from the command land. Happy to say your suggestion worked! 

Working on windows can be a bit of a pain sometimes :(

Thanks for your help!

All the best,
Peter

**Comment by jwindhager** [comment]
Great, and thanks for letting me know!
